### ISSUE TITLE
Streams der Privaten Sender nur noch in SD

### ISSUE THREAD

**Issue by mattipunkt** [sunsettrack4/telerising#14]
Seit ca. 2 Wochen sind die Streams von den privaten Sendern nur in SD (480p). Dabei sind die Streams der öffentlich-rechtlichen in Full-HD (Upscaled 720p, weil Deutsches öffentliches Fernsehen). Zattoo Unlimited ist abonniert. 
Die Bandbreite ist auf 8000 gestellt. 
Wenn man das Skript startet tauchen keine Fehler auf. 

Wie kann man die Sender der privaten wieder in HD bekommen?

**Comment by sunsettrack4** [comment]
Sofern noch das alte Skript zattoo_tvh verwendet wird, gibt es darüber keine Möglichkeit mehr, bitte daher auf das neue Skript umsteigen.

https://github.com/sunsettrack4/telerising/blob/master/README.md

**Comment by mattipunkt** [comment]
Es wird aber das neuste Skript (Telerising Version 0.3.6) verwendet.

**Comment by sunsettrack4** [comment]
Full HD wird bei den privaten Sendern nur mit HLS5 als Plattform unterstützt. Bitte das Setup nochmals prüfen.

Zattoo DE läuft bei mir soweit einwandfrei und mit allen Sendern in Full HD.
