### ISSUE TITLE
Zattoo: unable to get token json file

### ISSUE THREAD

**Issue by torsk** [sunsettrack4/telerising#19]
telerising does not start today: Given info in terminal is:

`ERROR - UNABLE TO LOGIN TO WEBSERVICE! (unable to get token json file)`

The response from the zattoo-server is hardly readable, says something like

`    lang="de">Es gab einen Fehler</div><div class="nosupText"
    lang="en">It looks like your browsers is outdated or not fully
    supported by us. For best TV experience please
    use</div><div class="nosupText" lang="de">MÃ¶glicherweise ist dein
    Browser veraltet oder wird von uns nicht voll unterstÃ¼tzt. FÃ¼r
    ein optimales TV-Erlebnis empfehlen
    wir</div><div class="nosupBrowserslist"><a class="nosupBrowser"`

Followed by `==== API PROCESS STOPPED! ====`

Is there something I can do?

TIA
Torsten

**Comment by sunsettrack4** [comment]
Fixed: 2f36cd01798ef9959eb7fc9f0eaa0d201ddddaea
