### ISSUE TITLE
A possibility of changing the using port without editing the script

### ISSUE THREAD

**Issue by Duell10111** [sunsettrack4/telerising#2]
Would it be possible to create a good solution for changing the port the scipt is using. For example for the case that a other application is already using port 8080. I am not very familar with the language perl so I do not know how the perfect solution to implement it.

**Comment by sunsettrack4** [comment]
Done: https://github.com/sunsettrack4/telerising/commit/951e61e237ba481126bf49a592d90e06ce67a9b8
