### ISSUE TITLE
[Erledigt] 1und1 Streaming "http_status 403"

### ISSUE THREAD

**Issue by Railsimulatornet** [sunsettrack4/telerising#22]
Guten Morgen,

leider funktioniert das Streaming nicht mehr mit 1&1. Aktuell habe ich die Version 0.4.6 installiert.

Ich erhalte die Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/29884757/107746205-b72f4000-6d15-11eb-80ac-b287b5b4b425.png)

{"internal_code": 401, "http_status": 403, "success": false}

**Comment by sunsettrack4** [comment]
Zattoo and the resellers don't support HLS anymore, please switch to HLS5.
