### ISSUE TITLE
Invalid Channel ID

### ISSUE THREAD

**Issue by pr0j3ctx** [sunsettrack4/telerising#23]
Hi.

Ich bekomme aktuell folgende Meldung. Das Script habe ich auf die aktuellste Version aktualisiert. Leider habe ich keine Ahnung wo das herkommt.

> * 2021-02-12 14:09:58 LIVE-TV prosieben | 5000 | hls - Loading Live URL
> X 2021-02-12 14:09:58 LIVE-TV prosieben | 5000 | hls - Invalid Channel ID
> RESPONSE:
> 
> {"internal_code": 401, "http_status": 403, "success": false}

Gruß

**Comment by sunsettrack4** [comment]
https://github.com/sunsettrack4/telerising/issues/22#issuecomment-778065004
