### ISSUE TITLE
wilmaa - only audio

### ISSUE THREAD

**Issue by mike8032** [sunsettrack4/telerising#7]
hi
if you request a wilmaa stream, you only get audio and the video is missing.
to reproduce this, setup up wilmaa as your source and request a stream.
thank you for checking.

**Comment by sunsettrack4** [comment]
VLC does not support HLS5, ffmpeg must be used.

**Comment by mike8032** [comment]
would you mind to specify your answer about ffmpeg? using the tag &platform=hls5&ffmpeg=true provides a playlist but only the audio is provided. i have ffmpeg installed on the system.

or is your answer based on that the stream needs to be piped over ffmpeg for example into tvheadend?

thank you for your answer.

**Comment by sunsettrack4** [comment]
> the stream needs to be piped over ffmpeg for example into tvheadend

Yes

**Comment by ItsEcholot** [comment]
What ffmpeg arguments did you use @mike8032 ?
